sudo: false
language: elixir
elixir:
  - 1.0.5
  - 1.1.0
  
notifications:
  recipients:
    - tim@buchwaldt.ws

otp_release:
  - 17.1
  - 18.0
  - 18.1
script:
  - mix compile --warnings-as-errors
  - mix test
services:
  - redis-server
